# Generated by Django 4.0 on 2021-12-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='タイトル')),
                ('content', models.TextField(null=True, verbose_name='本文')),
                ('author', models.TextField(null=True, verbose_name='作者')),
                ('released_at', models.DateTimeField(null=True, verbose_name='発表年')),
            ],
            options={
                'verbose_name_plural': 'Lyric',
            },
        ),
    ]
