# Generated by Django 4.0 on 2021-12-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('word_cloud', '0002_remove_lyric_author_lyric_composer_lyric_lyricist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='word_cloud_img',
            field=models.ImageField(null=True, upload_to='', verbose_name='ワードクラウド'),
        ),
    ]
